spring.application.name=auth-service

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/shopsharper_auth?createDatabaseIfNotExist = true
spring.datasource.password=Rohit@2004
spring.datasource.username=root

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format-sql=true


logging.level.root=debug


secret.key = jafjkdfkjadbkjdajfba4654dsdknfnakjdf
expiration=3600000


razorpay.key.id=rzp_test_TAAKHjIryP3cOq

razorpay.key.secret=Ob5o3a4my1K1gJ5JR61iSyXC


